# Generated by Django 5.0.6 on 2024-06-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=200)),
                ('esalary', models.IntegerField()),
                ('erole', models.CharField(max_length=200)),
            ],
        ),
    ]
